server:
  port: 8080

spring:
  application:
    name: Api Gateway

service:
  product:
    url: http://localhost:8081
  order:
    url: http://localhost:8082
  payment:
    url: http://localhost:8084
  shipping:
    url: http://localhost:8083
logging:
  level:
    root: INFO
  file:
    name: log.txt
